#type: args

model:
  input_with_mask: True
  n_groups: 2
  n_group_inner_layers: 1
  param_sharing_strategy: "inner_group"
  dim_model: 256
  dim_hidden: 512
  num_heads: 8
  dim_k: 32
  dim_v: 32
  dropout: 0
  diagonal_attention_mask: True
  reconstruction_loss_weight: 1
  imputation_loss_weight: 1
  MIT: True

train:
  epochs: 200
  lr: 0.001
  itr_per_epoch: 1.0e+8
  save_strategy: "best"
  optimizer_type: "adam"
  lr_scheduler:

diffusion: